In [23]:
#1. Write a program to test whether none of the elements of a given numpy array is zero.

import numpy as np

test_array = np.array([1,3,-2,5,0,11,0,12])

def test(array):
    for i in range(len(test_array)):
        if test_array[i]==0:
            return True
        else:
            return False
        
test(test_array)

False

In [33]:
#2. Write a python program to create an element-wise comparison (greater, greater_equal, less and
# less_equal) of two given numpy arrays.

x_array = np.array([3,1,6,7,0])
y_array = np.array([7,8,-1,2,0])


list1 = []

for i in range(len(x_array)):
    if x_array[i] > y_array[i]:
        list1.append('Greater')
    elif x_array[i] > y_array[i] and x_array[i] == y_array[i]:
        list1.append('Greater_equal')
    elif x_array[i] < y_array[i]:
        list1.append('Less')
    elif x_array[i] == x_array[i]:
        list1.append('Equal')
    else:
        list1.append('Less_equal')
        

In [34]:
list1

['Less', 'Less', 'Greater', 'Greater', 'Equal']

In [42]:
#3. Write a program to create a 3x3 numpy matrix with values ranging from 2 to 10.

matrix_array = np.arange(2,11).reshape(3,3)

matrix_array

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [52]:
#4. Write a program that takes a 2D numpy array as input and returns a new array containing only
# the even-indexed rows and columns.

array_1 = np.array([[1,3,5,6,7],
                   
                   [8,9,2,0,10]])
new_array = []
for i in range(len(array_1)):
    for j in range(len(array_1[i])):
        
        if i%2 == 0 and j%2==0:
            new_array.append(array_1[i][j])
            
print(new_array)

[1, 5, 7]


In [66]:
#5. Write a program to create a 2D numpy array with 1 on the border and 0 inside.



row = 10
cols = 8


array = np.zeros((row,cols))


array[0,:]=1
array[-1,:]=1
array[:,0]=1
array[:,-1]=1
array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [59]:
#6. Write a program that replace all odd number in a 3D numpy array with 0.

array = np.array([[[1,44,6,7,0],[9,2,5,8,11],[11,6,53,23,34]]])

for i in range(len(array)):
    for j in range(len(array[i])):
        for z in range(len(array[i][j])):
            
            if array[i][j][z] % 2 == 0:
                pass
            else:
                array[i][j][z] = 0
                
array

array([[[ 0, 44,  6,  0,  0],
        [ 0,  2,  0,  8,  0],
        [ 0,  6,  0,  0, 34]]])